version: '3.6'
services:
  mongodb:
    image: mongo:6.0
    container_name: ddev-${DDEV_SITENAME}-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
